### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [adedov/libiqxmlrpc#7]
After boostorg/system@2fa0a00583a3a7 build fails. See [error log](https://ptpb.pw/u7H7).

```c++
libiqxmlrpc/ssl_lib.cc:33:29: error: expected class name
class LockContainer: boost::noncopyable {
                            ^
1 error generated.
```

**Comment by adedov** [comment]
Hi, I gladly accept PR-s. Thanks

**Comment by RadekSimkanic** [comment]
Hi, I have similar problem with Boost 1.7.0
I get following error during build:
```
libiqxmlrpc/libiqxmlrpc/ssl_lib.cc:33:41: error: expected class-name before ‘{’ token
 class LockContainer: boost::noncopyable {
                                         ^
```
